ktor:
  environment: "$JELLYFISH_ENV:prod"

  deployment:
    port: 8080

  application:
    modules:
      - com.kamelia.jellyfish.ApplicationKt.module

liquibase:
  master: "classpath:db/db.changelog-master.xml"

jellyfish:
  uploadFolder: "$JELLYFISH_UPLOAD_FOLDER:uploads"

  jwt:
    secretAccess: $JELLYFISH_JWT_SECRET
    expirationAccess: "$JELLYFISH_JWT_EXPIRATION:3600000" # Default 1 hour
    secretRefresh: $JELLYFISH_JWT_SECRET_REFRESH
    expirationRefresh: "$JELLYFISH_JWT_EXPIRATION_REFRESH:2592000000" # Default 30 days
    realm: jellyfish login-locked
