ktor:
  environment: "$HEDERA_ENV:prod"

  deployment:
    port: "$HEDERA_PORT:8080"

  application:
    modules:
      - com.kamelia.hedera.ApplicationKt.module

liquibase:
  master: "classpath:db/db.changelog-master.xml"

hedera:
  url: "$HEDERA_URL:http://localhost:3000"
  uploadFolder: "$HEDERA_UPLOAD_FOLDER:uploads"
  thumbnailFolder: "$HEDERA_UPLOAD_FOLDER:thumbnails"
  globalConfigurationFile: "$HEDERA_GLOBAL_CONFIGURATION_FILE:global_configuration.json"
  searchMaxDistance: "$HEDERA_SEARCH_MAX_DISTANCE:0.85"
  loginThrottle: "$HEDERA_LOGIN_THROTTLE:3000" # Default 3 seconds

  jwt:
    secretAccess: $HEDERA_JWT_SECRET
    expirationAccess: "$HEDERA_JWT_EXPIRATION:3600000" # Default 1 hour
    secretRefresh: $HEDERA_JWT_REFRESH_SECRET
    expirationRefresh: "$HEDERA_JWT_REFRESH_EXPIRATION:2592000000" # Default 30 days
    secretWSToken: $HEDERA_JWT_WS_SECRET
    expirationWSToken: "$HEDERA_JWT_WS_EXPIRATION:300000" # Default 5 minutes
    realm: hedera login-locked

  database:
    host: "$HEDERA_DATABASE_HOST:localhost"
    port: "$HEDERA_DATABASE_PORT:5432"
    name: "$HEDERA_DATABASE_NAME:hedera"
    username: "$HEDERA_DATABASE_USERNAME:hedera"
    password: "$HEDERA_DATABASE_PASSWORD:hedera"

  mail:
    host: "$HEDERA_MAIL_HOST:127.0.0.1"
    port: "$HEDERA_MAIL_PORT:587"
    tls: "$HEDERA_MAIL_TLS:true"
    auth: "$HEDERA_MAIL_AUTH:true"
    username: "$HEDERA_MAIL_USERNAME"
    password: "$HEDERA_MAIL_PASSWORD"
    from: "$HEDERA_MAIL_FROM"
    fromName: "$HEDERA_MAIL_FROM_NAME:Hedera"
