ktor:
  environment: "$HEDERA_ENV:prod"

  deployment:
    port: "$HEDERA_PORT:8080"

  application:
    modules:
      - com.kamelia.hedera.ApplicationKt.module

liquibase:
  master: "classpath:db/db.changelog-master.xml"

hedera:
  uploadFolder: "$HEDERA_UPLOAD_FOLDER:uploads"

  jwt:
    secretAccess: $HEDERA_JWT_SECRET
    expirationAccess: "$HEDERA_JWT_EXPIRATION:3600000" # Default 1 hour
    secretRefresh: $HEDERA_JWT_REFRESH_SECRET
    expirationRefresh: "$HEDERA_JWT_REFRESH_EXPIRATION:2592000000" # Default 30 days
    secretWSToken: $HEDERA_JWT_WS_SECRET
    expirationWSToken: "$HEDERA_JWT_WS_EXPIRATION:300000" # Default 5 minutes
    realm: hedera login-locked
