version: '3'
services:
  hederadb:
    image: postgres:alpine
    container_name: hederadb
    environment:
      - POSTGRES_USER=hedera
      - POSTGRES_PASSWORD=hedera
      - DB_NAME=hedera
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_EXTENSIONS=pg_trgm
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  data:
    driver: local
